# Generated by Django 4.2.6 on 2023-10-08 02:27

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo ?')),
                ('plano', models.CharField(max_length=50, verbose_name='Plano')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo ?')),
                ('servico', models.CharField(max_length=100, verbose_name='Serviço')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='media/servicos', variations={'thumb': {'crop': True, 'height': 168, 'width': 196}}, verbose_name='imagem')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo ?')),
                ('preco', models.CharField(max_length=100, verbose_name='Preço')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plano', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Preço',
                'verbose_name_plural': 'Preços',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo ?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('avaliacao', models.TextField(max_length=300, verbose_name='Avaliação')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='media/cliente', variations={'thumb': {'crop': True, 'height': 225, 'width': 225}}, verbose_name='Imagem')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plano', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
