# Generated by Django 4.2.6 on 2023-10-08 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plano',
            options={'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='imagem',
        ),
    ]
